/* Generated by tools/import_lynx_art.py -- do not edit. */
#ifndef LYNX_ART_H
#define LYNX_ART_H

#define ART_SPRITE_BYTES 49
#define ART_TILE_RAW_BYTES 32
#define ART_TILE_COUNT 52
#define ART_PLAYER_FRAMES 12

/* TGI palettes, one per server palette_id: 16 green bytes then 16
   blue/red bytes each. Index 0 is the overworld / boot palette. */
#define ART_PALETTE_COUNT 3
extern const unsigned char art_clut[ART_PALETTE_COUNT][32];
/* Terrain tiles as raw 4bpp framebuffer bytes (8 rows x 4 bytes) for
   the CPU tile blitter, which is the only terrain path. Object tiles
   are precomposed opaque over the ground they stand on. */
extern const unsigned char art_tiles_raw[52][ART_TILE_RAW_BYTES];
extern const unsigned char art_player[12][ART_SPRITE_BYTES];
extern const unsigned char art_beaver[ART_SPRITE_BYTES];
extern const unsigned char art_snake[ART_SPRITE_BYTES];
extern const unsigned char art_goblin[ART_SPRITE_BYTES];
extern const unsigned char art_slime0[ART_SPRITE_BYTES];
extern const unsigned char art_slime1[ART_SPRITE_BYTES];
extern const unsigned char art_bat0[ART_SPRITE_BYTES];
extern const unsigned char art_bat1[ART_SPRITE_BYTES];
extern const unsigned char art_gorvak[ART_SPRITE_BYTES];
extern const unsigned char art_wilhelm[ART_SPRITE_BYTES];
extern const unsigned char art_wilhelm_working[ART_SPRITE_BYTES];
extern const unsigned char art_bullet[ART_SPRITE_BYTES];
extern const unsigned char art_item_gold[ART_SPRITE_BYTES];
extern const unsigned char art_item_sticks[ART_SPRITE_BYTES];
extern const unsigned char art_item_herb[ART_SPRITE_BYTES];
extern const unsigned char art_item_potion[ART_SPRITE_BYTES];
extern const unsigned char art_item_key[ART_SPRITE_BYTES];

/* 4x5 font, ASCII 32..95, 5 bytes per glyph (row bits 3..0). */
extern const unsigned char art_font4x5[64 * 5];

#endif
