#!/usr/bin/env python3
"""Turn the sound effects below into src/sound_data.c for src/sound.c.

An effect is a list of segments (wave, Hz from, Hz to, ms, volume from,
volume to). Volume is 0-63 (the DAC's range). Pitch and volume glide
linearly across a segment, updated every TICK timer counts. For "noise", Hz
is the rate the noise steps at.

Each segment is stored as 8 bytes: timer count, count change per step,
volume * 4, its change per step, steps, flags (bit 0 noise, bits 5-4 the
log2 of how many FIRQs a tone's half cycle spans)."""

from __future__ import annotations

import sys

CLOCK = 3579545          # GIME timer input with $FF91 bit 5 set
TICK = 32768             # timer counts per glide step (about 9.2 ms)
MAX_COUNT = 4095         # the 12-bit timer
MIN_COUNT = 400          # keeps the FIRQ rate (and its CPU cost) bounded

# sound.h SND_* order, from 1.
EFFECTS = {
    "shoot": [
        ("noise", 7000, 7000, 10, 40, 30),
        ("tone", 1800, 500, 120, 44, 6),
    ],
    "hurt": [
        ("noise", 3000, 1500, 50, 56, 30),
        ("tone", 220, 150, 140, 44, 0),
    ],
    "death": [
        ("tone", 392, 392, 150, 44, 36),
        ("tone", 330, 330, 150, 44, 36),
        ("tone", 262, 262, 150, 44, 36),
        ("tone", 262, 110, 450, 44, 0),
    ],
    "kill": [
        ("tone", 600, 1500, 60, 40, 44),
        ("noise", 6000, 1200, 180, 48, 0),
    ],
    "levelup": [
        ("tone", 523, 523, 75, 40, 36),
        ("tone", 659, 659, 75, 40, 36),
        ("tone", 784, 784, 75, 40, 36),
        ("tone", 1047, 1047, 260, 44, 0),
    ],
}


def fail(message: str) -> None:
    sys.exit(f"sound_gen: {message}")


def segment(name: str, wave: str, hz0: float, hz1: float, ms: float,
            v0: int, v1: int) -> bytes:
    noise = wave == "noise"
    # A tone flips every half cycle; noise steps once per count.
    c0 = CLOCK / hz0 / (1 if noise else 2)
    c1 = CLOCK / hz1 / (1 if noise else 2)
    shift = 0
    while max(c0, c1) / (1 << shift) > MAX_COUNT:
        shift += 1
    if noise and shift:
        fail(f"{name}: noise below {CLOCK // MAX_COUNT} Hz")
    if shift > 3:
        fail(f"{name}: tone below {CLOCK // (2 * MAX_COUNT * 8)} Hz")
    c0 /= 1 << shift
    c1 /= 1 << shift
    if min(c0, c1) < MIN_COUNT:
        fail(f"{name}: {max(hz0, hz1)} Hz is too high")
    ticks = round(ms * CLOCK / 1000 / TICK)
    if not 1 <= ticks <= 255:
        fail(f"{name}: {ms} ms is out of range")
    dcount = round((c1 - c0) / ticks)
    if not 0 <= v0 <= 63 or not 0 <= v1 <= 63:
        fail(f"{name}: volume out of 0-63")
    # The DAC is $FF20 bits 7-2: volume * 4, so a glide can move in quarter
    # steps. Truncated so a fade never overshoots past 0.
    dvol = int((v1 - v0) * 4 / ticks)
    end_vol = v0 * 4 + dvol * ticks
    if not 0 <= end_vol <= 255 or not -128 <= dvol <= 127:
        fail(f"{name}: volume glide overflows")
    count = round(c0)
    if not MIN_COUNT <= count + dcount * ticks <= MAX_COUNT:
        fail(f"{name}: pitch glide leaves the timer's range")
    flags = (1 if noise else 0) | (shift << 4)
    # Big-endian, as the 6809 loads it.
    return bytes([count >> 8, count & 0xFF, (dcount >> 8) & 0xFF, dcount & 0xFF,
                  v0 * 4, dvol & 0xFF, ticks, flags])


def main() -> None:
    out = sys.argv[1]
    data = bytearray()
    starts = [0]
    for name, segs in EFFECTS.items():
        starts.append(len(data))
        for seg in segs:
            data += segment(name, *seg)
        data += bytes(8)  # 0 ticks: the end
    lines = ["/* Generated by tools/sound_gen.py -- do not edit. */", "",
             "const unsigned char sound_segs[] = {"]
    for i in range(0, len(data), 8):
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in data[i:i + 8]) + ",")
    lines += ["};", "",
              "const unsigned sound_start[] = { " + ", ".join(map(str, starts)) + " };"]
    with open(out, "w") as f:
        f.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
