#!/usr/bin/env python3
"""Convert the Lynx tileset into Amiga planar art for the FujiRealm client.

Source of truth is lynx-client/art/lynx_tileset.json (8x8 tiles, 16-colour
CLUT). Parsing, the object-over-ground compositing table and the per-map
palette tints are imported from the Lynx importer so the two clients cannot
drift apart.

Output (C, for m68k-amigaos-gcc):
  * art_palette[ART_PALETTE_COUNT][16]  12-bit 0x0RGB colours for LoadRGB4
  * art_tiles[52][4][16]                16x16 terrain, 4 bitplanes, one UWORD
                                        per row (8x8 art doubled); object
                                        tiles precomposed over their ground
  * art_sprites[N][4][16], art_masks[N][16]
                                        players then entities, with a 1-plane
                                        mask (pen != 0) for masked blits
  * ART_SPRITE_* indices for the entity sprites

Usage: amiga_art.py <out.c> <out.h>
"""
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[1]
sys.path.insert(0, str(REPO / "lynx-client" / "tools"))

import import_lynx_art as lynx  # noqa: E402  (after sys.path setup)

DEPTH = 4
SIZE = 16


def doubled(rows):
    """8x8 pen rows -> 16x16 by pixel doubling."""
    out = []
    for row in rows:
        wide = [p for p in row for _ in (0, 1)]
        out.append(wide)
        out.append(list(wide))
    return out


def planes(pixels):
    """16x16 pens -> [plane][row] UWORDs, leftmost pixel in bit 15."""
    result = []
    for plane in range(DEPTH):
        words = []
        for row in pixels:
            value = 0
            for pen in row:
                value = (value << 1) | ((pen >> plane) & 1)
            words.append(value)
        result.append(words)
    return result


def planes8(pixels):
    """8x8 pens -> [plane][row] bytes, leftmost pixel in bit 7."""
    result = []
    for plane in range(DEPTH):
        rows = []
        for row in pixels:
            value = 0
            for pen in row:
                value = (value << 1) | ((pen >> plane) & 1)
            rows.append(value)
        result.append(rows)
    return result


def mask(pixels):
    words = []
    for row in pixels:
        value = 0
        for pen in row:
            value = (value << 1) | (1 if pen else 0)
        words.append(value)
    return words


def rgb12(rgb):
    r, g, b = rgb
    return ((r >> 4) << 8) | ((g >> 4) << 4) | (b >> 4)


def load():
    data = json.loads(lynx.TILESET.read_text(encoding="utf-8"))
    clut = [tuple(int(c.lstrip("#")[i:i + 2], 16) for i in (0, 2, 4))
            for c in data["palette"]]
    tiles = sorted(data["tiles"], key=lambda t: t["index"])
    tile_rows = [lynx.rows_from_hex(t["rows"], f"tile {t['index']}") for t in tiles]
    players = sorted(data["players"], key=lambda p: p["index"])
    player_rows = [lynx.rows_from_hex(p["rows"], f"player {p['index']}")
                   for p in players]
    by_name = {e["name"]: e for e in data["entities"]}
    names = [name for name, _, _ in lynx.ENTITY_SPRITES]
    entity_rows = [lynx.rows_from_hex(by_name[n]["rows"], f"entity {n}") for n in names]
    return clut, tile_rows, player_rows, names, entity_rows


def composite(tile_rows):
    """Object tiles drawn over the ground they stand on (pen 0 -> ground)."""
    out = []
    for index, rows in enumerate(tile_rows):
        base = lynx.OBJECT_TILE_BASE.get(index)
        if base is not None:
            ground = tile_rows[base]
            rows = [[ground[y][x] if rows[y][x] == 0 else rows[y][x]
                     for x in range(8)] for y in range(8)]
        out.append(rows)
    return out


def c_words(words):
    return ", ".join(f"0x{w:04X}" for w in words)


def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    out_c, out_h = Path(sys.argv[1]), Path(sys.argv[2])
    clut, tile_rows, player_rows, names, entity_rows = load()
    tiles = [planes(doubled(r)) for r in composite(tile_rows)]
    # Native 8x8 tiles for the splash screen's tile lettering: each row in
    # the high byte of a UWORD, so the sheet is a 16-wide bitmap.
    tiles8 = [[[w << 8 for w in plane] for plane in planes8(r)]
              for r in composite(tile_rows)]
    sprite_pixels = [doubled(r) for r in player_rows + entity_rows]
    palettes = [[rgb12(c) for c in lynx.tint(clut, *t)] for t in lynx.PALETTE_TINTS]

    h = ["/* Generated by tools/amiga_art.py from lynx-client/art/lynx_tileset.json."
         " Do not edit. */",
         "#ifndef FUJIREALM_AMIGA_ART_H", "#define FUJIREALM_AMIGA_ART_H", "",
         "#include <exec/types.h>", "",
         f"#define ART_TILE_SIZE {SIZE}", f"#define ART_DEPTH {DEPTH}",
         f"#define ART_TILE_COUNT {len(tiles)}",
         f"#define ART_PLAYER_COUNT {len(player_rows)}",
         f"#define ART_SPRITE_COUNT {len(sprite_pixels)}",
         f"#define ART_PALETTE_COUNT {len(palettes)}"]
    for i, name in enumerate(names):
        h.append(f"#define ART_SPRITE_{name.upper()} {len(player_rows) + i}")
    h += ["",
          "extern const UWORD art_palette[ART_PALETTE_COUNT][16];",
          "extern const UWORD art_tiles[ART_TILE_COUNT][ART_DEPTH][ART_TILE_SIZE];",
          "extern const UWORD art_sprites[ART_SPRITE_COUNT][ART_DEPTH][ART_TILE_SIZE];",
          "extern const UWORD art_masks[ART_SPRITE_COUNT][ART_TILE_SIZE];",
          "extern const UWORD art_tiles8[ART_TILE_COUNT][ART_DEPTH][8];",
          "", "#endif", ""]

    c = ["/* Generated by tools/amiga_art.py from lynx-client/art/lynx_tileset.json."
         " Do not edit. */", f'#include "{out_h.name}"', "",
         "const UWORD art_palette[ART_PALETTE_COUNT][16] = {"]
    for pal in palettes:
        c.append(f"    {{ {c_words(pal)} }},")
    c += ["};", "", "const UWORD art_tiles[ART_TILE_COUNT][ART_DEPTH][ART_TILE_SIZE] = {"]
    for index, tile in enumerate(tiles):
        c.append(f"    {{ /* {index} */")
        c += [f"        {{ {c_words(p)} }}," for p in tile]
        c.append("    },")
    c += ["};", "",
          "const UWORD art_sprites[ART_SPRITE_COUNT][ART_DEPTH][ART_TILE_SIZE] = {"]
    labels = [f"player {i}" for i in range(len(player_rows))] + names
    for label, pixels in zip(labels, sprite_pixels):
        c.append(f"    {{ /* {label} */")
        c += [f"        {{ {c_words(p)} }}," for p in planes(pixels)]
        c.append("    },")
    c += ["};", "", "const UWORD art_masks[ART_SPRITE_COUNT][ART_TILE_SIZE] = {"]
    for label, pixels in zip(labels, sprite_pixels):
        c.append(f"    {{ {c_words(mask(pixels))} }}, /* {label} */")
    c += ["};", "", "const UWORD art_tiles8[ART_TILE_COUNT][ART_DEPTH][8] = {"]
    for index, tile in enumerate(tiles8):
        c.append(f"    {{ /* {index} */")
        c += [f"        {{ {c_words(p)} }}," for p in tile]
        c.append("    },")
    c += ["};", ""]

    out_c.parent.mkdir(parents=True, exist_ok=True)
    out_c.write_text("\n".join(c), encoding="utf-8")
    out_h.write_text("\n".join(h), encoding="utf-8")


if __name__ == "__main__":
    main()
