#!/usr/bin/env python3
"""Export the world maps as tile ids for the stats page's map view.

The page draws one coloured pixel per tile, so all it needs is the tile id
grid. Taking it from the server's own world builders (``server/world.py``)
rather than re-parsing ``maps/*.csv`` in PHP means the page can never disagree
with what players actually walk on: the CSVs are a *legend* of symbols, and
duplicating that legend in another language is exactly the kind of second
implementation that drifts.

    python3 tools/export_map_json.py

Writes ``server/map_data.json``, which ``server/stats.php`` reads. Re-run after
editing ``maps/*.csv`` and re-importing them.
"""

from __future__ import annotations

import base64
import json
import pathlib
import sys

REPO_ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from server.world import (  # noqa: E402
    WORLD_H,
    WORLD_W,
    build_overworld,
    build_pvp_realm,
    build_starter_cave,
)

OUT_PATH = REPO_ROOT / "server" / "map_data.json"

# map_id -> (display name, builder). Ids match protocol.MAP_* so the page can
# place a player straight from their saved map_id.
MAPS = {
    0: ("Overworld", build_overworld),
    1: ("Starter Cave", build_starter_cave),
    2: ("PvP Realm", build_pvp_realm),
}


def main() -> int:
    maps = {}
    for map_id, (name, build) in MAPS.items():
        world = build(0)  # seed is unused: these layouts are hand-authored
        tiles = bytes(
            world.tile(x, y) for y in range(world.height) for x in range(world.width)
        )
        maps[str(map_id)] = {
            "name": name,
            "width": world.width,
            "height": world.height,
            # One byte per tile, row-major, base64'd: 12 KB of tiles becomes a
            # 16 KB string the page decodes with atob().
            "tiles": base64.b64encode(tiles).decode("ascii"),
        }
        print(f"map {map_id} {name}: {world.width}x{world.height}")

    OUT_PATH.write_text(
        json.dumps(
            {
                "_comment": (
                    "Generated by tools/export_map_json.py from server/world.py. "
                    "Do not edit by hand; regenerate instead."
                ),
                "width": WORLD_W,
                "height": WORLD_H,
                "maps": maps,
            }
        )
        + "\n"
    )
    print(f"wrote {OUT_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
