#!/usr/bin/env python3
"""Write the MADS include that defines client server connection defaults."""

from __future__ import annotations

import sys
from pathlib import Path


MAX_HOST_LEN = 32
DEFAULT_HYBRID_PORT = 9000
DEFAULT_LOGIN_PORT = 9010


def parse_port(value: str, name: str) -> int:
    try:
        port = int(value, 10)
    except ValueError as exc:
        raise ValueError(f"{name} must be a decimal integer") from exc
    if not 1 <= port <= 65535:
        raise ValueError(f"{name} must be between 1 and 65535")
    return port


def render_config(host: str, hybrid_port: int, login_port: int) -> str:
    try:
        encoded = host.encode("ascii")
    except UnicodeEncodeError as exc:
        raise ValueError("SERVER_HOST must be ASCII") from exc
    if not encoded:
        raise ValueError("SERVER_HOST must not be empty")
    if len(encoded) > MAX_HOST_LEN:
        raise ValueError(f"SERVER_HOST must be {MAX_HOST_LEN} bytes or less")
    if not 1 <= hybrid_port <= 65535:
        raise ValueError("HYBRID_SERVER_PORT must be between 1 and 65535")
    if not 1 <= login_port <= 65535:
        raise ValueError("LOGIN_SERVER_PORT must be between 1 and 65535")

    host_bytes = ",".join(str(byte) for byte in encoded)
    login_suffix_bytes = ",".join(
        str(byte) for byte in f":{login_port}/".encode("ascii")
    )
    swapped_port = ((hybrid_port & 0xFF) << 8) | (hybrid_port >> 8)
    return (
        "; Generated by tools/write_server_host_default.py\n"
        "; Override with: make SERVER_HOST=hostname "
        "HYBRID_SERVER_PORT=9000 LOGIN_SERVER_PORT=9010\n"
        f"HYBRID_SERVER_PORT = {hybrid_port}\n"
        f"LOGIN_SERVER_PORT = {login_port}\n"
        f"NETSTREAM_PORT_SWAPPED = ${swapped_port:04X}\n"
        "server_host_default\n"
        f"        dta {host_bytes}\n"
        "SERVER_HOST_DEFAULT_LEN = *-server_host_default\n"
        "n_devicespec_suffix\n"
        f"        dta {login_suffix_bytes}\n"
        "N_DEVICESPEC_SUFFIX_LEN = *-n_devicespec_suffix\n"
    )


def main() -> int:
    if len(sys.argv) == 3:
        host, output_arg = sys.argv[1:]
        hybrid_arg = str(DEFAULT_HYBRID_PORT)
        login_arg = str(DEFAULT_LOGIN_PORT)
    elif len(sys.argv) == 5:
        host, hybrid_arg, login_arg, output_arg = sys.argv[1:]
    else:
        print(
            "usage: write_server_host_default.py HOST [HYBRID_PORT LOGIN_PORT] OUTPUT",
            file=sys.stderr,
        )
        return 2

    try:
        hybrid_port = parse_port(hybrid_arg, "HYBRID_SERVER_PORT")
        login_port = parse_port(login_arg, "LOGIN_SERVER_PORT")
        content = render_config(host, hybrid_port, login_port)
    except ValueError as exc:
        print(str(exc), file=sys.stderr)
        return 2

    output = Path(output_arg)
    output.parent.mkdir(parents=True, exist_ok=True)
    if output.exists() and output.read_text() == content:
        return 0
    output.write_text(content)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
