#!/usr/bin/env python3
"""Generate Atari build includes for the configured remote-player slot count."""

from __future__ import annotations

import argparse
from pathlib import Path


MIN_REMOTE_PLAYER_SLOTS = 1
MAX_REMOTE_PLAYER_SLOTS = 12
ARRAY_NAMES = (
    "remote_x",
    "remote_y",
    "remote_facing",
    "remote_alive",
    "remote_anim",
    "old_remote_x",
    "old_remote_y",
    "old_remote_alive",
)


def zero_list(count: int) -> str:
    return ",".join("0" for _ in range(count))


def write_build_options(path: Path, slots: int, pmg_player: int) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "; Generated by tools/write_remote_player_options.py\n"
        f"BUILD_REMOTE_PLAYER_SLOTS = {slots}\n"
        f"BUILD_PMG_PLAYER = {pmg_player}\n"
    )


def write_arrays(path: Path, slots: int) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = ["; Generated by tools/write_remote_player_options.py"]
    for name in ARRAY_NAMES:
        lines.append(name)
        lines.append(f"        dta {zero_list(slots)}")
    path.write_text("\n".join(lines) + "\n")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("slots", type=int)
    parser.add_argument("build_options")
    parser.add_argument("arrays")
    parser.add_argument(
        "pmg_player",
        nargs="?",
        default="1",
        help="1 to draw the local player with Player/Missile Graphics, 0 for the character sprite",
    )
    return parser.parse_args()


def parse_flag(value: str, name: str) -> int:
    normalized = value.strip().lower()
    if normalized in ("1", "on", "yes", "true"):
        return 1
    if normalized in ("0", "off", "no", "false"):
        return 0
    raise SystemExit(f"{name} must be 0 or 1, got {value!r}")


def main() -> int:
    args = parse_args()
    if not MIN_REMOTE_PLAYER_SLOTS <= args.slots <= MAX_REMOTE_PLAYER_SLOTS:
        raise SystemExit(
            f"REMOTE_PLAYER_SLOTS must be {MIN_REMOTE_PLAYER_SLOTS}..{MAX_REMOTE_PLAYER_SLOTS}, got {args.slots}"
        )
    pmg_player = parse_flag(args.pmg_player, "PMG_PLAYER")
    write_build_options(Path(args.build_options), args.slots, pmg_player)
    write_arrays(Path(args.arrays), args.slots)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
